Fixed [MPIR-405] regression in the maven site rendering + [MPIR-406] dependencies sorting
apache/maven-project-info-reports-plugin pull request #29
Opened 2022-01-20 10:57 UTC by sultan

https://issues.apache.org/jira/browse/MPIR-405

Maven Site Plugin and Doxia switching to HTML 5 broke all the reports that includes images.
Including other report plugins.
The proposed fix allows to return back to the original compact format that was more synthetic.

https://issues.apache.org/jira/browse/MPIR-406

Dependencies are now sorted in the report which eases search and visual control of exclusions

2022-01-26 10:43 UTC, michael-o requested changes
Retain the alt text by using the attibutes. See: https://github.com/apache/maven-doxia/blob/8013887518a46c5c7403bcb3b23845390b1ff202/doxia-core/src/main/java/org/apache/maven/doxia/sink/impl/Xhtml5BaseSink.java#L1041-L1061

2022-01-27 11:06 UTC, michael-o approved these changes
LGTM. I will test again and then merge.

2022-01-27 11:51 UTC, closed without merging

2025-06-15 09:04 UTC, jira-importer commented
Resolve #256

2025-06-15 09:09 UTC, jira-importer commented
Resolve #256