[MPIR-460] Dependency Information for maven-plugin
apache/maven-project-info-reports-plugin pull request #69
Opened 2024-06-02 14:19 UTC by slawekjaranowski

https://issues.apache.org/jira/browse/MPIR-460

2024-06-02 14:26 UTC, michael-o requested changes

2024-06-02 14:26 UTC, michael-o commented on src/it/MPIR-460-jar/verify.groovy
> +assert report.contains('Groovy Grap')
Grape, not Grap

2024-06-02 14:26 UTC, michael-o commented on src/it/MPIR-460-jar/verify.groovy
> +assert report.contains('Gradle/Grail')
Grails

2024-06-02 14:26 UTC, michael-o commented on src/it/MPIR-460-jar/pom.xml
> +    Coordinate list are generated for many tools
Coordinates

2024-06-02 14:26 UTC, michael-o commented on src/it/MPIR-460-maven-plugin/pom.xml
> +    Only coordinate for Maven plugin is generated
Coordinates

2024-06-02 14:26 UTC, michael-o commented on src/it/MPIR-460-maven-plugin/verify.groovy
> +assert !report.contains('Groovy Grap')
Same here

2024-06-02 14:26 UTC, michael-o commented on src/it/MPIR-460-maven-plugin/verify.groovy
> +assert !report.contains('Gradle/Grail')
Same here

2024-06-02 14:26 UTC, michael-o commented on src/main/java/org/apache/maven/report/projectinfo/DependencyInformationReport.java
> +            endSection();
`...Coordinates()`

2024-06-02 14:43 UTC, michael-o approved these changes
Looks totally reasonable to me.

2024-06-02 15:29 UTC, merged

2025-06-15 09:05 UTC, jira-importer commented
Resolve #350

2025-06-15 09:11 UTC, jira-importer commented
Resolve #350